import { type NextPage } from 'next'

import { useRouter } from 'next/router'

import { signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import Link from 'next/link'

import { trpc } from 'utils/trpc'

const Home: NextPage = () => {
    const router = useRouter()
    const { org } = router.query

    // const hello = trpc.example.hello.useQuery({ text: 'from the homepage' })
    // const { data: sessionData } = useSession()

    const { data: user } = trpc.member.me.useQuery()
    // const { data: post } = trpc.member.test.useQuery()
    const mutation = trpc.member.connectOrg.useMutation()
    console.log('mutation', mutation)

    // console.log('post', post?.categories[0]?.category)
    console.log('user', user)
    console.log('orgs', user?.organizations)

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#85C9C1] to-[#15162c]">
                <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                    <h1 className="text-white text-5xl font-extrabold tracking-tight sm:text-[5rem]">
                        Avat
                        <span className="text-[hsl(280,100%,70%)]">a</span>r
                        Stud<span className="text-[hsl(280,100%,70%)]">i</span>o
                    </h1>
                    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
                        <h3 className="text-2xl font-bold">Organizations</h3>
                        <div className="text-lg">
                            {user?.organizations[0]?.name}
                        </div>
                        <h3 className="text-2xl font-bold">Projects</h3>
                        <div className="text-lg">{user?.projects[0]?.name}</div>
                    </div>
                    <div className="flex flex-col items-center gap-2">
                        <p className="text-white text-2xl">
                            {/* {hello.data
                                ? hello.data.greeting
                                : 'Loading tRPC query...'} */}
                        </p>
                    </div>
                    <button
                        className="bg-white/10 text-white hover:bg-white/20 px-10 py-3 font-semibold no-underline transition"
                        onClick={() => mutation.mutate()}
                    >
                        Accept Invitation
                    </button>
                    <button
                        className="bg-white/10 text-white hover:bg-white/20 px-10 py-3 font-semibold no-underline transition"
                        onClick={() => signOut()}
                    >
                        Sign Out
                    </button>
                </div>
            </main>
        </>
    )
}

export default Home
