import { type NextPage } from 'next'

import { useRouter } from 'next/router'

import { signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import Link from 'next/link'

import { trpc } from 'utils/trpc'

const Org: NextPage = () => {
    const router = useRouter()
    const { slug } = router.query

    // const hello = trpc.example.hello.useQuery({ text: 'from the homepage' })
    // const { data: sessionData } = useSession()

    const { data: user } = trpc.member.me.useQuery()

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#85C9C1] to-[#15162c]">
                <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 "></div>
            </main>
        </>
    )
}

export default Org
