import { type NextPage } from 'next'
import NextError from 'next/error'

import { useRouter } from 'next/router'
import Head from 'next/head'
import Link from 'next/link'

import { trpc } from 'utils/trpc'

const Org: NextPage = () => {
    const router = useRouter()
    const slug = router.query.org as string

    // const hello = trpc.example.hello.useQuery({ text: 'from the homepage' })
    // const { data: sessionData } = useSession()

    const { data: user } = trpc.member.me.useQuery()

    console.log('slug', slug)
    const { data: org, error, status } = trpc.org.getBySlug.useQuery(slug)

    if (error) {
        return (
            <NextError
                title={error.message}
                statusCode={error.data?.httpStatus ?? 500}
            />
        )
    }
    if (status !== 'success') {
        return <div>Loading...</div>
    }

    const { name } = org

    return (
        <>
            <Head>
                <title>{name}</title>
                {/* <meta name="description" content="Generated by create-t3-app" /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#85C9C1] to-[#15162c]">
                <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                    <div className="text-white text-4xl font-bold">{name}</div>
                    <div className="text-white text-2xl font-bold">
                        Projects
                    </div>
                </div>
            </main>
        </>
    )
}

export default Org
