import Button, { ButtonType } from 'components/Button'
import { type NextPage } from 'next'
import NextError from 'next/error'
import Head from 'next/head'
import Link from 'next/link'

import { trpc } from 'utils/trpc'
import { usePrivy } from '@privy-io/react-auth'
import { useRouter } from 'next/router'

const Home: NextPage = () => {
    const router = useRouter()
    const trpcUtils = trpc.useContext()
    const { data: user, error, status, refetch } = trpc.member.me.useQuery()
    const mutation = trpc.member.acceptOrgInvitation.useMutation({
        onSuccess: () => trpcUtils.member.me.invalidate(),
    })

    const { logout: privyLogout, user: privyUser } = usePrivy()

    console.log('user', user?.invitations)

    const logout = async () => {
        await privyLogout()
        router.push('/')
    }

    if (error) {
        return (
            <NextError
                title={error.message}
                statusCode={error.data?.httpStatus ?? 500}
            />
        )
    }

    if (status !== 'success') {
        return <div>Loading...</div>
    }

    const Invitations = () => {
        const invitations = user?.invitations || []
        return invitations.length > 0 ? (
            <div className="flex flex-col items-center gap-2">
                {invitations.map(
                    ({ role, organization, organizationId, status }) => {
                        return status === 'PENDING' ? (
                            <div
                                key={`${organizationId}_${role}`}
                                className="flex items-center gap-2"
                            >
                                <div className="text-lg">
                                    {organization.name}
                                </div>
                                <Button
                                    text="Accept Invitation"
                                    onClick={() =>
                                        mutation.mutate({
                                            organizationId,
                                            role,
                                        })
                                    }
                                />
                            </div>
                        ) : null
                    },
                )}
            </div>
        ) : (
            <></>
        )
    }

    const Organizations = () => {
        const organizations = user?.organizations || []
        return organizations.length > 0 ? (
            <div>
                {organizations.map(({ name, slug }) => (
                    <Link
                        className="block text-lg hover:text-teal-200"
                        key={slug}
                        href={`/org/${slug}`}
                    >
                        {name}
                    </Link>
                ))}
            </div>
        ) : (
            <></>
        )
    }

    return (
        <>
            <Head>
                <title>Earnable Avatar Studio</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-black to-black">
                <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                    <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
                        Home
                    </h1>
                    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
                        <h3 className="text-2xl font-bold">Organizations</h3>
                        <Organizations />
                        <h3 className="text-2xl font-bold"></h3>
                        <Invitations />
                    </div>
                    <Button
                        text="Log Out"
                        onClick={logout}
                        type={ButtonType.Secondary}
                    />
                </div>
            </main>
        </>
    )
}

export default Home
