import { usePrivy } from '@privy-io/react-auth'
import FullPageLoading from 'components/FullPageLoading'
import OldButton from 'components/OldButton'
import { type NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import { pageToLoad } from 'utils'
import { trpc } from 'utils/trpc'

const Home: NextPage = () => {
    const router = useRouter()
    const { login, authenticated, ready } = usePrivy()
    const { data: user } = trpc.member.me.useQuery(undefined, { enabled: authenticated })
    // trpc.project.deleteAllMembers.useQuery()
    useEffect(() => {
        const page = pageToLoad(user)
        if (authenticated && user) router.push(page)
    }, [authenticated, router, user])

    if (!ready || (ready && authenticated)) return <FullPageLoading />
    return (
        <>
            <Head>
                <title>Earnable Avatar Studio</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {authenticated ? null : (
                <main className="flex min-h-[calc(100vh_-_120px)] flex-col items-center justify-center bg-black bg-jupiter-pattern">
                    <div className="container flex flex-col items-center justify-center gap-8 px-4 py-12">
                        <h1 className="text-5xl font-extrabold tracking-tight text-teal-100 sm:text-[5rem]">
                            Earnable Avatar Studio
                        </h1>
                        <div className="text-2xl text-teal-100">
                            Earn traits by participating and contributing to your community
                        </div>
                        <div className="flex flex-col items-center gap-2">
                            <div className="flex flex-col items-center justify-center gap-4">
                                <OldButton text="log in" onClick={login} />
                            </div>
                        </div>
                    </div>
                </main>
            )}
        </>
    )
}

export default Home
