import { usePrivy } from '@privy-io/react-auth'
import FullPageLoading from 'components/FullPageLoading'
import { type NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import robonova from 'public/assets/Robo Nova Homepage.png'
import shefiLogo from 'public/assets/shefi_logo.svg'
import { useEffect } from 'react'
import { pageToLoad } from 'utils'
import { trpc } from 'utils/trpc'

const Home: NextPage = () => {
    const router = useRouter()
    const { login, authenticated, ready } = usePrivy()
    const { data: user } = trpc.member.homePage.useQuery(undefined, { enabled: authenticated })

    useEffect(() => {
        if (authenticated && user) router.push(pageToLoad(user))
    }, [authenticated, router, user])

    if (!ready || (ready && authenticated)) return <FullPageLoading />
    return (
        <>
            <Head>
                <title>Earnable Avatar Studio</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {authenticated ? null : (
                <main className="flex min-h-[calc(100vh_-_120px)] flex-col items-center justify-center bg-black bg-sheFi bg-cover">
                    <div className="container flex flex-col items-center justify-center gap-10 px-4 py-12">
                        <div className="flex flex-col items-center md:flex-row md:items-end">
                            <div className="mr-8 flex flex-col items-end md:mr-0">
                                <div className="relative aspect-[2.66] h-auto w-[344px]  sm:w-[440px]  md:w-[480px] lg:w-[630px] xl:w-[720px]">
                                    <Image src={shefiLogo} alt="SheFi Logo" fill />
                                </div>
                                {/* <Image src={shefiLogo} alt="SheFi Logo" width={630} /> */}
                                <div className="">
                                    <span className=" font- whitespace-nowrap bg-gradient-to-b from-[rgb(252,255,121)] to-[rgb(44,173,226)] bg-clip-text font-robonova text-[3.3rem] leading-[1] text-transparent drop-shadow sm:text-[4.2rem] md:text-[4.6rem] lg:text-[6rem] xl:text-[6.9rem]">
                                        ROBO NOVA
                                    </span>
                                </div>
                            </div>
                            <div className="mx-auto w-80 sm:w-auto">
                                <Image src={robonova} alt="Robonova" height={400} />
                            </div>
                        </div>
                        <div className="font-robonova text-lg text-teal-50 sm:text-2xl">
                            Earn traits by participating in and contributing to SheFi
                        </div>
                        <div className="flex flex-col items-center gap-2">
                            <div className="flex flex-col items-center justify-center gap-4">
                                <button className="btn-primary w-56" onClick={login}>
                                    Log In
                                </button>
                            </div>
                        </div>
                    </div>
                </main>
            )}
        </>
    )
}

export default Home
