import { usePrivy } from '@privy-io/react-auth'
import FullPageLoading from 'components/FullPageLoading'
import { type NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import robonova from 'public/assets/Robo Nova Homepage.png'
import shefiLogo from 'public/assets/shefi_logo.svg'
import { useEffect } from 'react'
import { pageToLoad } from 'utils'
import { trpc } from 'utils/trpc'

const Home: NextPage = () => {
    const router = useRouter()
    const { login, authenticated, ready } = usePrivy()
    const { data: user } = trpc.member.homePage.useQuery(undefined, { enabled: authenticated })

    useEffect(() => {
        if (authenticated && user) router.push(pageToLoad(user))
    }, [authenticated, router, user])

    if (!ready || (ready && authenticated)) return <FullPageLoading />
    return (
        <>
            <Head>
                <title>Earnable Avatar Studio</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {authenticated ? null : (
                <main className="flex min-h-[calc(100vh_-_120px)] flex-col items-center justify-center bg-black bg-sheFi bg-cover">
                    <div className="container flex flex-col items-center justify-center gap-8 px-4 py-12">
                        <div className="flex flex-col items-end md:flex-row">
                            <div className="flex flex-col items-end">
                                <Image src={shefiLogo} alt="SheFi Logo" width={630} />
                                <div className="">
                                    <span className=" whitespace-nowrap bg-gradient-to-b from-[rgb(252,255,121)] to-[rgb(44,173,226)] bg-clip-text font-robonova text-5xl text-transparent drop-shadow sm:text-8xl">
                                        ROBO NOVA
                                    </span>
                                </div>
                            </div>
                            <Image src={robonova} alt="Robonova" height={320} className="mx-auto" />
                        </div>
                        <div className="font-robonova text-2xl text-teal-50">
                            Earn traits by participating and contributing to SheFi
                        </div>
                        <div className="flex flex-col items-center gap-2">
                            <div className="flex flex-col items-center justify-center gap-4">
                                <button className="btn-primary w-56" onClick={login}>
                                    Log In
                                </button>
                            </div>
                        </div>
                    </div>
                </main>
            )}
        </>
    )
}

export default Home
