import { type NextPage } from 'next'
import NextError from 'next/error'

import Head from 'next/head'
import { useRouter } from 'next/router'

import { trpc } from 'utils/trpc'

const Project: NextPage = () => {
    const router = useRouter()
    const slug = router.query.project as string

    const {
        data: project,
        error,
        status,
    } = trpc.project.getBySlug.useQuery(slug, { enabled: !!slug })

    const { data: user } = trpc.member.me.useQuery()

    // check is user is an org admin
    const isOrgAdmin = user?.organizations?.find(
        (org) => project?.organizationId === org.id,
    )

    if (error) {
        return (
            <NextError
                title={error.message}
                statusCode={error.data?.httpStatus ?? 500}
            />
        )
    }
    if (status !== 'success') {
        return <div>Loading...</div>
    }

    const { name, id } = project

    // a component that loops through the traits category array, and has the trait category as the header, and the traits listed below
    const Traits = () => {
        return (
            <>
                {project.traitCategories.map((category) => {
                    return (
                        <div key={category.name}>
                            <h2>{category.name}</h2>
                            <h3>{category.zIndex}</h3>
                            <ul>
                                {category.traits.map((trait) => (
                                    <li key={trait.name}>{trait.name}</li>
                                ))}
                            </ul>
                        </div>
                    )
                })}
            </>
        )
    }

    return (
        <>
            <Head>
                <title>{name}</title>
                {/* <meta name="description" content="Generated by create-t3-app" /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <div className="relative flex min-h-screen flex-col ">
                    <div className="mx-auto grid w-full max-w-7xl grid-cols-1 lg:grid-cols-2 xl:px-8">
                        {/* Left sidebar & main wrapper */}
                        {/* Start right half */}
                        <div className="col-span-1">
                            <div className=" h-full py-6 pl-4 pr-6 sm:pl-6 lg:pl-8 xl:pl-0">
                                <div className="relative h-full">
                                    <div className="flex flex-col">
                                        <div className="text-center text-4xl font-bold">
                                            {name}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {/* End right half */}

                        {/* Right half */}
                        <div className="col-span-1">
                            <div className="h-full  py-6 px-4 sm:px-6 lg:px-8">
                                <div className="relative h-full">
                                    <div className="text-center text-4xl font-bold">
                                        Traits
                                    </div>
                                    <Traits />
                                </div>
                            </div>
                        </div>
                        {/* End main area */}
                    </div>
                </div>
            </>
        </>
    )
}

export default Project
