import { type NextPage } from 'next'
import NextError from 'next/error'

import Head from 'next/head'

import { trpc } from 'utils/trpc'

const Project: NextPage = () => {
    const { data: project, error, status } = trpc.project.getProject.useQuery()

    const { data: user } = trpc.member.me.useQuery()

    // check is user is an org admin
    const isOrgAdmin = user?.organizations?.find((org) => project?.organizationId === org.id)

    if (error) {
        return <NextError title={error.message} statusCode={error.data?.httpStatus ?? 500} />
    }
    if (status !== 'success') {
        return <div>Loading...</div>
    }

    const { name, id } = project

    // a component that loops through the traits category array, and has the trait category as the header, and the traits listed below
    const Traits = () => {
        return (
            <>
                {project.traitCategories.map((category) => {
                    return (
                        <div key={category.name}>
                            <div>{category.name}</div>
                            <div>{category.zIndex}</div>
                            <div>Modifiable: {category.isModifiable.toString()}</div>
                            <div className="grid grid-cols-3 content-evenly  gap-3">
                                {category.traits.map(({ name, pngUrl }) => (
                                    <div key={name} className="flex flex-col items-center">
                                        <img src={pngUrl} width={100} height={100} alt={name} />
                                        <div>{name}</div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )
                })}
            </>
        )
    }

    const data = Object.entries({ 1: project.members, b: project.members })

    return (
        <>
            <Head>
                <title>{name}</title>
                {/* <meta name="description" content="Generated by create-t3-app" /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <div className="relative flex min-h-screen flex-col ">
                    <div className="mx-auto grid w-full max-w-7xl grid-cols-1 lg:grid-cols-2 xl:px-0">
                        {/* Left sidebar & main wrapper */}
                        {/* Start right half */}
                        <div className="col-span-1">
                            <div className=" h-full py-6 pl-4 pr-6 sm:pl-6 xl:pl-0">
                                <div className="relative h-full">
                                    <div className="flex flex-col">
                                        <div className="text-center text-4xl font-bold">{name}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {/* End right half */}

                        {/* Right half */}
                        <div className="col-span-1">
                            <div className="h-full py-6 px-4 sm:px-6 xl:pr-0">
                                <div className="relative h-full">
                                    <div className="text-center text-4xl font-bold">Traits</div>
                                    <Traits />
                                </div>
                            </div>
                        </div>
                        {/* End main area */}
                    </div>
                </div>
            </>
        </>
    )
}

export default Project
