import { type NextPage } from 'next'
import NextError from 'next/error'

import { UserCircleIcon } from '@heroicons/react/24/outline'

import Head from 'next/head'
import { useRouter } from 'next/router'

import { truncateAddress } from 'utils'
import { trpc } from 'utils/trpc'

const Project: NextPage = () => {
    const router = useRouter()
    // const slug = router.query.project as string

    const { data: project, error, status } = trpc.project.getProject.useQuery()

    const { data: user, status: userStatus } = trpc.member.me.useQuery()
    // check is user is an org admin
    // const isOrgAdmin = user?.organizations?.find((o) => o.id == project?.id)

    if (error) {
        return <NextError title={error.message} statusCode={error.data?.httpStatus ?? 500} />
    }
    if (status !== 'success' || userStatus !== 'success') {
        return <div>Loading...</div>
    }

    const { name, slug } = project
    const hasMinted = user.nftMetadata.length > 0

    const Members = () => {
        const members =
            project.members.map(({ member, role }) => {
                return { ...member, role }
            }) || []
        return members.length > 0 ? (
            <div>
                {members.map(({ firstName, lastName, address, role }) => (
                    <div className="mt-2 flex items-center" key={address}>
                        {/* <Link className="text-lg hover:text-teal-200" href={`/project/${slug}`}> */}
                        <UserCircleIcon className="mr-2 inline-block h-8 w-8" />
                        {firstName} {lastName} ({role.toLowerCase()}) {truncateAddress(address)}
                        {/* </Link> */}
                    </div>
                ))}
            </div>
        ) : (
            <></>
        )
    }

    return (
        <>
            <Head>
                <title>{name}</title>
                {/* <meta name="description" content="Generated by create-t3-app" /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <div className="relative flex min-h-screen flex-col">
                    {/* 3 column wrapper */}
                    <div className="mx-auto w-full max-w-7xl flex-grow  lg:flex xl:px-8">
                        {/* Left sidebar & main wrapper */}
                        <div className="min-w-0 flex-1  xl:flex">
                            <div className="border-b border-gray-200 xl:w-64 xl:flex-shrink-0 xl:border-b-0 xl:border-r xl:border-gray-200">
                                <div className="h-full py-6 pl-4 pr-6 sm:pl-6 lg:pl-8 xl:pl-0">
                                    {/* Start left column area */}
                                    <div className="relative h-full">
                                        <div className="flex flex-col">
                                            <div className="text-4xl font-bold">{name}</div>
                                            <button
                                                className="btn-primary mt-4 self-start text-center"
                                                onClick={() => {
                                                    router.push(`/project/${slug}/pfp-ui`)
                                                }}
                                            >
                                                {hasMinted ? `Update Avatar` : `Mint Avatar`}
                                            </button>
                                        </div>
                                    </div>
                                    {/* End left column area */}
                                </div>
                            </div>

                            <div className="lg:min-w-0 lg:flex-1">
                                <div className="h-full py-6 px-4 sm:px-6 lg:px-8">
                                    {/* Start main area*/}
                                    <div className="relative h-full">
                                        <div className="text-4xl font-bold">Members</div>
                                        <Members />
                                    </div>
                                    {/* End main area */}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </>
        </>
    )
}

export default Project
