import Spinner from 'components/Spinner'
import Head from 'next/head'

const FullPageLoading: React.FC = () => {
    return (
        <>
            <Head>
                <title>loading...</title>
                {/* <meta name="description" content="Generated by create-t3-app" /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <div className="container relative mx-auto flex min-h-[calc(100vh_-_120px)] items-center justify-center">
                    <Spinner />
                </div>
            </>
        </>
    )
}

export default FullPageLoading
