import Spinner from 'components/Spinner'
import Head from 'next/head'

interface FullPageLoadingProps {
    loadingText?: string
}

const FullPageLoading: React.FC<FullPageLoadingProps> = ({ loadingText }) => {
    return (
        <>
            <Head>
                <title>loading...</title>
                {/* <meta name="description" content="Generated by create-t3-app" /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <div className="container relative mx-auto flex min-h-[calc(100vh_-_120px)] items-center justify-center">
                    {loadingText ? (
                        <div className="flex flex-col items-center gap-4">
                            <Spinner />
                            <div className="text-center text-lg text-teal-400"> {loadingText}</div>
                        </div>
                    ) : (
                        <Spinner />
                    )}
                </div>
            </>
        </>
    )
}

export default FullPageLoading
