import Head from 'next/head'

type ShellProps = {
    LeftChild: JSX.Element
    RightChild: JSX.Element
    Header?: JSX.Element
    pageTitle: string
    leftWidth?: 'third' | 'half'
}

const Shell: React.FC<ShellProps> = ({ LeftChild, RightChild, Header, pageTitle, leftWidth = 'third' }) => {
    const width = leftWidth === 'third' ? 'sm:w-4/12' : 'sm:w-6/12'
    return (
        <>
            <Head>
                <title>{pageTitle}</title>
                {/* <meta name="description" content="Generated by create-t3-app" /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                {/* Background color split screen for large screens */}
                <div className="relative flex min-h-[calc(100vh_-_120px)] flex-col">
                    {/* page wrapper */}
                    <div className="container mx-auto">{Header}</div>
                    <div className="container mx-auto w-full flex-grow lg:flex xl:px-8">
                        {/* Left sidebar & main wrapper */}
                        <div className="min-w-0 flex-1 sm:flex">
                            {/* Start left column area */}
                            <div className={`sm:flex-shrink-0 ` + width}>
                                <div className="h-full py-6 pl-4 pr-6 sm:pl-6 lg:pl-8 xl:pl-0">
                                    <div className="relative h-full">{LeftChild}</div>
                                </div>
                            </div>
                            {/* End left column area */}

                            {/* Start main area*/}
                            <div className="sm:min-w-0 sm:flex-1">
                                <div className="h-full py-6 px-4 sm:px-6 lg:px-8">
                                    <div className="relative h-full">{RightChild}</div>
                                </div>
                            </div>
                            {/* End main area */}
                        </div>
                    </div>
                </div>
            </>
        </>
    )
}

export default Shell
