import Head from 'next/head'
import React from 'react'

type ShellProps = {
    children?: React.ReactNode
    Header?: JSX.Element
    pageTitle: string
    leftWidth?: 'third' | 'half'
}

const Shell: React.FC<ShellProps> = ({ children, Header, pageTitle, leftWidth = 'third' }) => {
    const [LeftChild, RightChild] = React.Children.toArray(children)
    const width = leftWidth === 'third' ? 'md:w-4/12' : 'md:w-6/12'
    return (
        <>
            <Head>
                <title>{pageTitle}</title>
                {/* <meta name="description" content="Generated by create-t3-app" /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                {/* Background color split screen for large screens */}
                <div className="relative flex min-h-[calc(100vh_-_120px)] flex-col">
                    {/* page wrapper */}
                    <div className="container mx-auto">{Header}</div>
                    <div className="container mx-auto w-full flex-grow lg:flex xl:px-8">
                        {/* Left sidebar & main wrapper */}
                        <div className="min-w-0 flex-1 md:flex">
                            {/* Start left column area */}
                            <div className={`md:flex-shrink-0 ` + width}>
                                <div className="h-full md:py-6">
                                    <div className="relative h-full">{LeftChild}</div>
                                </div>
                            </div>
                            {/* End left column area */}

                            {/* Start main area*/}
                            <div className="md:min-w-0 md:flex-1">
                                <div className="h-full md:py-6">
                                    <div className="relative h-full">{RightChild}</div>
                                </div>
                            </div>
                            {/* End main area */}
                        </div>
                    </div>
                </div>
            </>
        </>
    )
}

export default Shell
