import { type NextPage } from 'next'

import Head from 'next/head'
import { useRouter } from 'next/router'

import { trpc } from 'utils/trpc'

const Org: NextPage = () => {
    const router = useRouter()

    const { data: user } = trpc.member.me.useQuery()

    const { data } = trpc.trait.getFromS3.useQuery('llama-pfp')
    const copyS3Files = trpc.trait.createFromS3.useMutation()

    // const Projects = () => {
    //     const projects = org.projects || []
    //     return projects.length > 0 ? (
    //         <div>
    //             {projects.map(({ name, slug }) => (
    //                 <div className="mt-2 flex items-center" key={slug}>
    //                     <Link
    //                         className="text-lg hover:text-teal-200"
    //                         href={`/project/${slug}`}
    //                     >
    //                         <UserCircleIcon className="mr-2 inline-block h-8 w-8" />
    //                         {name}
    //                     </Link>
    //                 </div>
    //             ))}
    //         </div>
    //     ) : (
    //         <></>
    //     )
    // }

    return (
        <>
            <Head>
                <title>Admin Dashboard</title>
                {/* <meta name="description" content="Generated by create-t3-app" /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <div className="relative flex min-h-screen flex-col">
                    {/* 3 column wrapper */}
                    <div className="mx-auto w-full max-w-7xl flex-grow  lg:flex xl:px-8">
                        {/* Left sidebar & main wrapper */}
                        <div className="min-w-0 flex-1  xl:flex">
                            <div className="border-b border-gray-200 xl:w-64 xl:flex-shrink-0 xl:border-b-0 xl:border-r xl:border-gray-200">
                                <div className="h-full py-6 pl-4 pr-6 sm:pl-6 lg:pl-8 xl:pl-0">
                                    {/* Start left column area */}
                                    <div className="relative h-full">
                                        <div className="flex flex-col">
                                            <div className="text-4xl font-bold">
                                                Admin
                                            </div>
                                            <div className="mt-4 mb-2 text-3xl font-bold">
                                                things
                                            </div>
                                            {/* <Projects /> */}
                                            <button
                                                onClick={() =>
                                                    copyS3Files.mutateAsync({
                                                        projectSlug:
                                                            'llama-pfp',
                                                    })
                                                }
                                                className="btn-primary"
                                            >
                                                upload files
                                            </button>
                                        </div>
                                    </div>
                                    {/* End left column area */}
                                </div>
                            </div>

                            <div className="lg:min-w-0 lg:flex-1">
                                <div className="h-full py-6 px-4 sm:px-6 lg:px-8">
                                    {/* Start main area*/}
                                    <div className="relative h-full">
                                        <div className="text-4xl font-bold">
                                            Members
                                        </div>
                                    </div>
                                    {/* End main area */}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </>
        </>
    )
}

export default Org
