import { type NextPage } from 'next'

import Head from 'next/head'
import { useRouter } from 'next/router'
import { useState } from 'react'

import { trpc } from 'utils/trpc'

const Org: NextPage = () => {
    const router = useRouter()

    const { data: user } = trpc.member.me.useQuery()

    const { data } = trpc.trait.getFromS3.useQuery('llama-pfp')
    const copyS3Files = trpc.trait.createFromS3.useMutation()

    const createOrg = trpc.org.createNewOrg.useMutation({
        onSuccess: (data) => {
            console.log('success', data)
        },
        onError: (error) => {
            console.log('error', error)
        },
    })

    const [newOrgName, setNewOrgName] = useState('')

    // const Projects = () => {
    //     const projects = org.projects || []
    //     return projects.length > 0 ? (
    //         <div>
    //             {projects.map(({ name, slug }) => (
    //                 <div className="mt-2 flex items-center" key={slug}>
    //                     <Link
    //                         className="text-lg hover:text-teal-200"
    //                         href={`/project/${slug}`}
    //                     >
    //                         <UserCircleIcon className="mr-2 inline-block h-8 w-8" />
    //                         {name}
    //                     </Link>
    //                 </div>
    //             ))}
    //         </div>
    //     ) : (
    //         <></>
    //     )
    // }

    return (
        <>
            <Head>
                <title>Admin Dashboard</title>
                {/* <meta name="description" content="Generated by create-t3-app" /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <>
                <div className="relative flex min-h-screen flex-col">
                    {/* 3 column wrapper */}
                    <div className="mx-auto w-full max-w-7xl flex-grow  lg:flex xl:px-8">
                        {/* Left sidebar & main wrapper */}
                        <div className="min-w-0 flex-1  xl:flex">
                            <div className="border-b border-gray-200 xl:w-64 xl:flex-shrink-0 xl:border-b-0 xl:border-r xl:border-gray-200">
                                <div className="h-full py-6 pl-4 pr-6 sm:pl-6 lg:pl-8 xl:pl-0">
                                    {/* Start left column area */}
                                    <div className="relative h-full">
                                        <div className="flex flex-col">
                                            <div className="text-4xl font-bold">Admin</div>
                                            <div className="mt-4 mb-2 text-3xl font-bold">things</div>
                                            {/* <Projects /> */}
                                            <div className="mt-2">
                                                <div className="relative rounded-md border border-gray-300 px-3 py-2 shadow-sm focus-within:border-teal-600 focus-within:ring-1 focus-within:ring-teal-600">
                                                    <label
                                                        htmlFor="name"
                                                        className="absolute -top-2 left-2 -mt-px inline-block bg-black  px-1 text-xs font-medium"
                                                    >
                                                        New Org Name
                                                    </label>
                                                    <input
                                                        type="text"
                                                        name="name"
                                                        id="name"
                                                        className="block border-0 bg-black p-0 text-teal-50 placeholder-gray-500 focus:ring-0 sm:text-sm"
                                                        placeholder="Haab Goblins Crypto Club"
                                                        value={newOrgName}
                                                        onChange={(e) => {
                                                            setNewOrgName(e.target.value)
                                                        }}
                                                    />
                                                </div>
                                                <button
                                                    className="btn-primary mt-2"
                                                    onClick={() => {
                                                        createOrg.mutate(newOrgName)
                                                    }}
                                                >
                                                    Create
                                                </button>
                                            </div>
                                            <button
                                                // onClick={() =>
                                                //     copyS3Files.mutateAsync({
                                                //         projectSlug: 'llama-pfp',
                                                //     })
                                                // }
                                                className="btn-primary mt-4"
                                            >
                                                upload files
                                            </button>
                                        </div>
                                    </div>
                                    {/* End left column area */}
                                </div>
                            </div>

                            <div className="lg:min-w-0 lg:flex-1">
                                <div className="h-full py-6 px-4 sm:px-6 lg:px-8">
                                    {/* Start main area*/}
                                    <div className="relative h-full">
                                        <div className="text-4xl font-bold">Members</div>
                                    </div>
                                    {/* End main area */}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </>
        </>
    )
}

export default Org
